### ISSUE TITLE
Weird code blocks appear when editing home page of my site

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/theme-ucsc#18]
![edit-page](https://user-images.githubusercontent.com/7795841/162839771-91bba85b-fab1-4bac-9681-3a7615e791e9.jpg)
In header and footer.

**Comment by knice** [comment]
That is the **site** editor area. If you are editing a _page_, you won't see the entire header and footer.

**Comment by knice** [comment]
Closing for now. We'll mention this issue if we change those blocks.

**Comment by knice** [comment]
[This issue is resolved in this commit](https://github.com/ucsc/ucsc-2022/commit/1b5ad3d7814273d8072b7bdf71ab0a79c1ca18d7) and will be included with the RC.2 release of the theme. We replaced the HTML code blocks with an SVG icon block provided by [The Icon Block](https://wordpress.org/plugins/icon-block/) plugin. The theme now depends on this plugin, but the developer is widely known and respected in the WP community. 

![screenshot-2022-04-26-172400](https://user-images.githubusercontent.com/36719/165414153-f5adceb9-ba07-4bd1-b5a6-63c329e36f81.jpg)
![screenshot-2022-04-26-172400](https://user-images.githubusercontent.com/36719/165414224-e8801a39-ef0c-46ee-81b2-6fb8e5a709ee.jpg)
